[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"
  functions = "./functions"

[context.production.environment]
  NODE_VERSION = "18.20.3"
